"""
Sync master credentials (.env.local) → all online fleet devices.

마스터 SSOT: D:/00.test/neo-genesis/.env.local (desktop-sol01)
↓ (Tailscale SSH + scp)
- desktop-yesol:  C:/Users/CTS_Sol/.neo-genesis/credentials.env  (chmod 600 not applicable on Windows)
- ysh-server:     /home/ysh/.neo-genesis/credentials.env         (chmod 600)
- mac-studio:     /Users/ysh/.neo-genesis/credentials.env        (chmod 600)

Mobile devices (s26-ultra / tab-s10-ultra) are EXCLUDED — approval-only role.

Reference: .agent/knowledge/MASTER_CREDENTIAL_ACCESS_STANDARD.md

Run:
    python scripts/sync_credentials_to_fleet.py             # all devices
    python scripts/sync_credentials_to_fleet.py --target ysh-server
    python scripts/sync_credentials_to_fleet.py --dry-run
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MASTER_ENV_LOCAL = ROOT / ".env.local"
MASTER_ENV = ROOT / ".env"
MERGED_ENV_TEMP = ROOT / ".env.fleet-sync-merged.tmp"  # gitignored, created at sync time


@dataclass
class FleetDevice:
    name: str
    ssh_host: str  # SSH alias or hostname
    target_path: str  # absolute path on the device
    transport: str  # "ssh-unix" or "ssh-windows"
    enabled: bool = True


# Fleet topology (from .agent/shared-brain/device_inventory.json)
DEVICES = [
    FleetDevice(
        name="desktop-yesol",
        ssh_host="desktop-yesol",
        target_path="/c/Users/CTS_Sol/.neo-genesis/credentials.env",
        transport="ssh-windows",
    ),
    FleetDevice(
        name="ysh-server",
        ssh_host="ysh-server",
        target_path="/home/ysh/.neo-genesis/credentials.env",
        transport="ssh-unix",
    ),
    FleetDevice(
        name="mx-macbuild-mac-studio",
        ssh_host="mac-studio",
        target_path="/Users/ysh/.neo-genesis/credentials.env",
        transport="ssh-unix",
    ),
]


def _parse_env(path: Path) -> dict[str, str]:
    """Parse .env file → ordered dict of key=value (preserves order, last wins)."""
    out: dict[str, str] = {}
    if not path.exists():
        return out
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\r\n").strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            k = k.strip()
            v = v.strip()
            if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
                v = v[1:-1]
            if k:
                out[k] = v
    return out


def build_merged_master() -> Path:
    """Merge .env + .env.local → .env.fleet-sync-merged.tmp (LF line endings, .env.local wins).

    This produces a single fleet-distributable credential file that contains the union of all
    master credentials with .env.local taking precedence for any key in both files.
    """
    base = _parse_env(MASTER_ENV)
    overrides = _parse_env(MASTER_ENV_LOCAL)
    merged: dict[str, str] = {**base, **overrides}  # .env.local wins

    lines = [
        "# Neo Genesis fleet master credentials (auto-generated by sync_credentials_to_fleet.py)",
        "# Source: .env (base) + .env.local (overrides). .env.local wins on conflict.",
        f"# Generated: {Path(__file__).name}",
        "# DO NOT EDIT — this is a snapshot of the master SSOT on desktop-sol01.",
        "",
    ]
    for k, v in merged.items():
        # Re-quote if value contains spaces or special chars; otherwise raw
        if any(c in v for c in (' ', '\t', '#', '"', "'")):
            v_safe = '"' + v.replace('\\', '\\\\').replace('"', '\\"') + '"'
        else:
            v_safe = v
        lines.append(f"{k}={v_safe}")

    # LF only (no CRLF) — Unix-safe
    content = "\n".join(lines) + "\n"
    MERGED_ENV_TEMP.write_text(content, encoding="utf-8", newline="\n")
    return MERGED_ENV_TEMP


def check_master() -> bool:
    if not MASTER_ENV_LOCAL.exists() and not MASTER_ENV.exists():
        print(f"ERROR: neither {MASTER_ENV_LOCAL} nor {MASTER_ENV} exists", file=sys.stderr)
        return False

    merged_path = build_merged_master()
    size = merged_path.stat().st_size
    n_keys = sum(1 for line in merged_path.read_text(encoding="utf-8").splitlines()
                 if line and not line.startswith("#") and "=" in line)
    print(f"[master] merged from .env + .env.local → {merged_path.name} ({size} bytes, {n_keys} keys)")
    return True


def is_device_online(device: FleetDevice, timeout: int = 5) -> bool:
    """Check Tailscale ping or SSH connection."""
    try:
        result = subprocess.run(
            ["ssh", "-o", "ConnectTimeout=" + str(timeout),
             "-o", "BatchMode=yes",
             "-o", "StrictHostKeyChecking=no",
             device.ssh_host, "echo OK"],
            capture_output=True, text=True, timeout=timeout + 2,
        )
        return result.returncode == 0 and "OK" in result.stdout
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return False


def sync_to_device(device: FleetDevice, dry_run: bool = False) -> bool:
    """Push master .env.local to device target_path with chmod 600 (Unix)."""
    print(f"\n[{device.name}] -> {device.target_path}")

    if not device.enabled:
        print(f"  [skip] disabled in config")
        return True

    if not is_device_online(device):
        print(f"  [skip] device offline (SSH connection failed)")
        return False

    if dry_run:
        print(f"  [dry-run] would scp + chmod 600")
        return True

    try:
        # Ensure target directory exists
        target_dir = Path(device.target_path).parent.as_posix()
        subprocess.run(
            ["ssh", device.ssh_host, f"mkdir -p {target_dir}"],
            check=True, timeout=10, capture_output=True,
        )

        # scp the merged master file
        scp_target = f"{device.ssh_host}:{device.target_path}"
        subprocess.run(
            ["scp", "-q", str(MERGED_ENV_TEMP), scp_target],
            check=True, timeout=30, capture_output=True,
        )

        # Normalize CRLF → LF (Unix only) + chmod 600
        if device.transport == "ssh-unix":
            # Strip \r if Windows line endings, then chmod
            normalize_cmd = (
                f"sed -i 's/\\r$//' {device.target_path} && "
                f"chmod 600 {device.target_path}"
            )
            subprocess.run(
                ["ssh", device.ssh_host, normalize_cmd],
                check=True, timeout=10, capture_output=True,
            )

        # Verify by counting non-comment KEY=value lines (size may differ due to LF vs CRLF)
        result = subprocess.run(
            ["ssh", device.ssh_host,
             f"grep -cE '^[A-Z_][A-Z0-9_]*=' {device.target_path}"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0:
            remote_keys = int(result.stdout.strip())
            local_keys = sum(1 for line in MERGED_ENV_TEMP.read_text(encoding="utf-8").splitlines()
                            if line and not line.startswith("#") and "=" in line)
            if remote_keys == local_keys:
                print(f"  [OK] {remote_keys} keys synced + chmod 600")
                return True
            else:
                print(f"  [WARN] key count mismatch — local {local_keys} vs remote {remote_keys}")
                return False
        else:
            print(f"  [WARN] verify failed: {result.stderr.strip()}")
            return False

    except subprocess.CalledProcessError as e:
        print(f"  [ERROR] {e.cmd}: returncode {e.returncode}")
        if e.stderr:
            print(f"    stderr: {e.stderr.decode('utf-8', errors='replace')[:200]}")
        return False
    except Exception as e:
        print(f"  [ERROR] {type(e).__name__}: {e}")
        return False


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Sync master credentials to fleet devices",
    )
    parser.add_argument("--target", help="Sync to specific device only (e.g. ysh-server)")
    parser.add_argument("--dry-run", action="store_true",
                       help="Show what would be done without actually syncing")
    args = parser.parse_args()

    if not check_master():
        return 1

    devices = DEVICES
    if args.target:
        devices = [d for d in DEVICES if d.name == args.target or d.ssh_host == args.target]
        if not devices:
            print(f"ERROR: device not found: {args.target}", file=sys.stderr)
            return 2

    print(f"\nSyncing to {len(devices)} device(s){' [DRY RUN]' if args.dry_run else ''}...")

    summary = {"ok": [], "failed": [], "skipped": []}
    for device in devices:
        ok = sync_to_device(device, dry_run=args.dry_run)
        if ok:
            summary["ok"].append(device.name)
        else:
            summary["failed"].append(device.name)

    print("\n" + "=" * 50)
    print("Summary:")
    for status, names in summary.items():
        if names:
            print(f"  {status}: {', '.join(names)}")

    return 0 if not summary["failed"] else 3


if __name__ == "__main__":
    sys.exit(main())
