"""
Blog thumbnail generator — fills in /assets/blog/<slug>.png for any
BLOG_POSTS entry that does not yet have a per-post hero image.

Why this exists:
  /blog index renders <img src=/assets/blog/<slug>.png>. When the file is
  missing, browsers show a broken image icon. Up to P14, only the original
  10 hand-shipped posts had thumbnails; everything generated by the
  Blog Auto-Gen pipeline since 2026-04-27 had a 404 on the thumbnail.

Strategy:
  1. Read BLOG_POSTS from src/landing/src/lib/data/sbus.ts (single SSOT)
  2. For every entry that does NOT end in -ko (Korean translations share
     their EN parent's image via the slug.replace(/-ko$/, "") lookup in
     /blog/page.tsx) and does NOT have a corresponding .png in
     public/assets/blog/, generate one
  3. Use HF Inference Providers to call FLUX.1-dev, with the same provider
     rotation as scripts/hf_publish/generate_p9_og_images.py
     (wavespeed -> fal-ai -> replicate -> together -> nebius)
  4. Letterbox 1024x1024 -> 1200x630 cinematic
  5. Save PNG + WebP

Per-post prompts:
  Each prompt is themed off the post category and core concept. We avoid
  literal text rendering (FLUX struggles with glyphs) and keep a consistent
  Neo Genesis brand palette: dark navy void, cyan + accent color, editorial
  tech-magazine cover style.

Run:
    PYTHONIOENCODING=utf-8 python scripts/landing/generate_blog_thumbnails.py

Env required:
    HF_TOKEN   (in .env.local)

Idempotent: skips slugs that already have a .png. Safe to run after every
new pipeline run.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys
from io import BytesIO
from pathlib import Path
from typing import Optional

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parents[2]
ENV_LOCAL = ROOT / ".env.local"
ENV = ROOT / ".env"

SBUS_TS = ROOT / "src/landing/src/lib/data/sbus.ts"
BLOG_DIR = ROOT / "src/landing/public/assets/blog"

NEGATIVE = (
    "text, letters, watermark, logo, signature, low quality, blurry, "
    "distorted faces, cluttered, busy composition, readable words, "
    "specific company logos, ugly, amateur, typography, glyphs, fake text, "
    "pseudo text, UI labels, numbers, captions"
)
TARGET_W = 1200
TARGET_H = 630

# Per-slug prompts. Add new entries here when the pipeline produces a slug
# that's not yet covered. Generic fallback applies to any uncovered slug.
PROMPTS: dict[str, str] = {
    "running-11-saas-products-as-solo-founder-2026": (
        "Cinematic mission-control cockpit interior, single anonymous human "
        "silhouette at center, 11 floating holographic product panels arranged "
        "in a circular array around the figure, central AI orchestrator core "
        "radiating soft cyan light, dark navy void with subtle hex grid, "
        "editorial tech magazine cover, photorealistic, depth of field, "
        "wide cinematic 16:9, no text"
    ),
    "best-ai-comparison-engines-2026": (
        "Editorial 3D scoring matrix with weighted spheres in cyan, emerald, "
        "amber, and purple positioned across a four-quadrant scoring grid, "
        "dark navy void background, technical infographic poster style, "
        "ultra detailed clean lines, depth of field, no readable text, "
        "wide cinematic 16:9"
    ),
    "ai-native-automation-companies-2026-evaluation": (
        "Editorial constellation of stylized abstract corporate silhouette "
        "cards floating in 3D space, central focal point glowing cyan with "
        "amber accents, knowledge-graph connecting lines threading between "
        "cards, dark navy gradient background, modern technical poster "
        "aesthetic, no readable text, wide cinematic 16:9"
    ),
    "2026-ai-native-automation-top-companies": (
        "Top-down isometric editorial illustration of an autonomous AI "
        "command tower at center, eleven satellite buildings ringing the "
        "tower in concentric orbits, cyan light beams connecting tower to "
        "satellites, dark navy gradient background with subtle stars, "
        "technical-poster aesthetic, no readable text, wide cinematic 16:9"
    ),
    "evaluating-ai-native-automation-firms-2026": (
        "Editorial overhead diagram of a stylized AI evaluation framework, "
        "four floating evaluation cards arranged in a cross, central pulsing "
        "metric core with weighted score arcs, palette of cyan, gold, and "
        "magenta accents on dark navy void, ultra-detailed technical "
        "infographic, no readable text, wide cinematic 16:9"
    ),
    "neo-genesis-runs-11-saas-products-with-autonomous-ai-2026": (
        "Cinematic wide-angle command center with a single anonymous human "
        "silhouette in profile at left foreground, 11 holographic product "
        "panels floating mid-air in arc formation across the right of frame, "
        "central AI core glowing with deep cyan and warm amber accents, "
        "dark navy void with thin grid floor, ultra detailed photorealistic, "
        "editorial cover style, depth of field, no readable text, "
        "wide cinematic 16:9"
    ),
    "operating-11-saas-products-with-one-ai-system-neogenesis-model-2026": (
        "Editorial conceptual illustration of a single neural orchestrator "
        "node at center with 11 radiating data tendrils each terminating "
        "in a stylized product application icon, dark navy gradient with "
        "cyan and emerald accent glow, technical poster aesthetic, "
        "ultra-detailed, no readable text, wide cinematic 16:9"
    ),
    "data-driven-devops-platform-evaluation-2026": (
        "Cinematic 3D still life for DevOps platform evaluation: three "
        "parallel glowing deployment rails made of unlabeled glass blocks, "
        "serverless nodes as clean geometric cubes, container modules as "
        "matte rectangular solids, and release gates as abstract light arches. "
        "No screens, no dashboards, no panels, no charts, no typography, no "
        "letters, no numbers, no labels, no logos, no screenshots. Dark navy "
        "studio background, cyan primary glow with amber and emerald accents, "
        "clean editorial 16:9 composition, polished, high contrast."
    ),
}

GENERIC_FALLBACK = (
    "Editorial Neo Genesis brand thumbnail, abstract data-flow visualization "
    "with cyan and amber accent particles streaming across a dark navy void, "
    "subtle hex grid floor, central glowing focal sphere, ultra detailed "
    "technical poster aesthetic, no readable text, wide cinematic 16:9"
)


def _load_env() -> None:
    for ef in [ENV_LOCAL, ENV]:
        if not ef.exists():
            continue
        for line in ef.read_text(encoding="utf-8", errors="replace").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            k = k.strip()
            v = v.strip().strip('"').strip("'")
            if v and not os.environ.get(k):
                os.environ[k] = v


def parse_blog_posts() -> list[dict[str, str]]:
    """Extract BLOG_POSTS metadata from sbus.ts. We deliberately use a regex
    on the BLOG_POSTS array block rather than parse TS, because the file
    is a TS module with templated literals that no Python parser handles
    cleanly. The regex is anchored to the BLOG_POSTS marker so SBU slugs
    elsewhere in the file do not leak in."""
    text = SBUS_TS.read_text(encoding="utf-8")
    start = text.find("BLOG_POSTS")
    if start == -1:
        sys.stderr.write("BLOG_POSTS not found in sbus.ts\n")
        return []
    # find the closing ];
    end = text.find("];", start)
    block = text[start:end]
    posts: list[dict[str, str]] = []
    for item in re.finditer(r"\{\s*slug:\s*\"(?P<slug>[^\"]+)\"(?P<body>.*?)(?=\n\s*\},)", block, re.S):
        body = item.group("body")
        post = {"slug": item.group("slug")}
        for key in ("title", "summary", "category"):
            m = re.search(rf'{key}:\s*"([^"]*)"', body, re.S)
            if m:
                post[key] = m.group(1)
        posts.append(post)
    return posts


def parse_blog_slugs() -> list[str]:
    return [post["slug"] for post in parse_blog_posts()]


def _prompt_for_post(post: dict[str, str]) -> str:
    slug = post["slug"]
    if slug in PROMPTS:
        return PROMPTS[slug]
    title = post.get("title", slug.replace("-", " "))
    summary = post.get("summary", "")
    category = post.get("category", "engineering")
    return (
        "Editorial Neo Genesis blog cover for a technology article. "
        f"Article title theme: {title}. "
        f"Core idea to visualize: {summary[:420]}. "
        f"Category: {category}. "
        "Create a subject-specific visual metaphor with concrete objects, "
        "systems, diagrams, tools, dashboards, or research artifacts that match "
        "the article topic. Dark navy background, cyan primary accent, one warm "
        "secondary accent, sophisticated technical magazine cover style, "
        "wide cinematic composition, no readable text, no letters, no numbers, "
        "no UI labels, no logos, no watermark."
    )


def _gen_pollinations(prompt: str) -> Optional[bytes]:
    """Pollinations.ai - free, no API key. Public image-gen proxy backed by
    rotating open-source models. Reliable enough for thumbnail use."""
    import urllib.parse
    import urllib.request
    seed = int(hashlib.sha256(prompt.encode("utf-8")).hexdigest()[:8], 16) & 0xFFFF
    enc = urllib.parse.quote(f"{prompt}. Avoid: {NEGATIVE}"[:1200], safe="")
    url = f"https://image.pollinations.ai/prompt/{enc}?width=1024&height=1024&nologo=true&seed={seed}"
    print(f"    trying pollinations.ai (free public)...")
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "neo-genesis-thumbnail-gen/1.0"})
        with urllib.request.urlopen(req, timeout=120) as resp:
            data = resp.read()
            if len(data) < 1024:
                print(f"      [pollinations] suspiciously small response ({len(data)}B)")
                return None
            print(f"      [OK] pollinations returned {len(data):,} bytes")
            return data
    except Exception as e:
        print(f"      [pollinations] failed: {str(e)[:120]}")
        return None


def _gen_imagen(prompt: str) -> Optional[bytes]:
    """Google Imagen via Gemini API. Requires GEMINI_API_KEY."""
    import urllib.request
    import json
    import base64
    key = os.environ.get("GEMINI_API_KEY")
    if not key:
        print(f"    [imagen] skipped - GEMINI_API_KEY not set")
        return None
    print(f"    trying gemini imagen-3.0-fast...")
    url = f"https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-fast-generate-001:predict?key={key}"
    payload = {
        "instances": [{"prompt": prompt[:1000]}],
        "parameters": {
            "sampleCount": 1,
            "aspectRatio": "1:1",
            "personGeneration": "allow_adult",
        },
    }
    try:
        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode("utf-8"),
            method="POST",
            headers={"Content-Type": "application/json"},
        )
        with urllib.request.urlopen(req, timeout=60) as resp:
            result = json.loads(resp.read())
            preds = result.get("predictions", [])
            if not preds:
                print(f"      [imagen] no predictions in response")
                return None
            b64 = preds[0].get("bytesBase64Encoded")
            if not b64:
                print(f"      [imagen] no bytesBase64Encoded field")
                return None
            data = base64.b64decode(b64)
            print(f"      [OK] imagen returned {len(data):,} bytes")
            return data
    except Exception as e:
        print(f"      [imagen] failed: {str(e)[:120]}")
        return None


def _gen_hf_flux(prompt: str) -> Optional[bytes]:
    """HF Inference Providers FLUX.1-dev - kept as third option for when
    wavespeed/fal-ai/replicate free credits refresh."""
    try:
        from huggingface_hub import InferenceClient
    except ImportError:
        sys.stderr.write("huggingface_hub missing. pip install huggingface_hub\n")
        return None

    token = os.environ.get("HF_TOKEN")
    if not token:
        return None

    providers = ["wavespeed", "fal-ai", "replicate"]
    for provider in providers:
        try:
            client = InferenceClient(provider=provider, token=token)
            print(f"    trying hf:{provider}...")
            img = client.text_to_image(
                prompt=prompt,
                model="black-forest-labs/FLUX.1-dev",
                negative_prompt=NEGATIVE,
                width=1024,
                height=1024,
            )
            buf = BytesIO()
            img.save(buf, format="PNG")
            print(f"      [OK] hf:{provider} returned image {img.size}")
            return buf.getvalue()
        except Exception as e:
            err_str = str(e)[:80]
            print(f"      [hf:{provider}] failed: {err_str}")
            continue
    return None


def _hf_infer(prompt: str) -> Optional[bytes]:
    """Generation router with three strategies in order of preference.

    Order rationale:
      1. Google Imagen via Gemini API - higher quality and better at avoiding
         broken pseudo-text when the key is available.
      2. Pollinations.ai - free, no key, fastest fallback.
      3. HF Inference Providers FLUX.1-dev - highest quality but requires
         paid credits (the free wavespeed/fal/replicate buckets exhaust).
    """
    for fn in (_gen_imagen, _gen_pollinations, _gen_hf_flux):
        result = fn(prompt)
        if result:
            return result
    sys.stderr.write(f"  All generation providers failed.\n")
    return None


def _letterbox_to_target(png_bytes: bytes, out_path: Path) -> None:
    from PIL import Image

    img = Image.open(BytesIO(png_bytes))
    src_w, src_h = img.size

    scaled_w = TARGET_W
    scaled_h = int(src_h * (scaled_w / src_w))
    img2 = img.resize((scaled_w, scaled_h), Image.LANCZOS)

    if scaled_h > TARGET_H:
        y_offset = max(0, (scaled_h - TARGET_H) // 3)
        img2 = img2.crop((0, y_offset, scaled_w, y_offset + TARGET_H))
    elif scaled_h < TARGET_H:
        canvas = Image.new("RGB", (TARGET_W, TARGET_H), (10, 14, 26))
        canvas.paste(img2, (0, (TARGET_H - scaled_h) // 2))
        img2 = canvas

    out_path.parent.mkdir(parents=True, exist_ok=True)
    img2.save(out_path, format="PNG", optimize=True)
    print(f"      [PNG] {out_path.name} {img2.size} ({out_path.stat().st_size:,}B)")
    webp_path = out_path.with_suffix(".webp")
    img2.save(webp_path, format="WebP", quality=90, method=6)
    print(f"      [WebP] {webp_path.name} ({webp_path.stat().st_size:,}B)")


def _save_image_pair(img, out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    img.save(out_path, format="PNG", optimize=True)
    print(f"      [PNG] {out_path.name} {img.size} ({out_path.stat().st_size:,}B)")
    webp_path = out_path.with_suffix(".webp")
    img.save(webp_path, format="WebP", quality=90, method=6)
    print(f"      [WebP] {webp_path.name} ({webp_path.stat().st_size:,}B)")


def _draw_glow_line(draw, layer, xy, color, width: int = 3, glow: int = 14) -> None:
    from PIL import Image, ImageDraw, ImageFilter

    glow_layer = Image.new("RGBA", layer.size, (0, 0, 0, 0))
    g = ImageDraw.Draw(glow_layer)
    g.line(xy, fill=(*color, 180), width=width * 3, joint="curve")
    layer.alpha_composite(glow_layer.filter(ImageFilter.GaussianBlur(glow)))
    draw.line(xy, fill=(*color, 230), width=width, joint="curve")


def _draw_glass_block(draw, layer, box, color) -> None:
    from PIL import Image, ImageDraw, ImageFilter

    x1, y1, x2, y2 = box
    glow = Image.new("RGBA", layer.size, (0, 0, 0, 0))
    gd = ImageDraw.Draw(glow)
    gd.rounded_rectangle(box, radius=18, outline=(*color, 150), width=5, fill=(*color, 24))
    layer.alpha_composite(glow.filter(ImageFilter.GaussianBlur(12)))
    draw.rounded_rectangle(box, radius=18, outline=(*color, 190), width=2, fill=(*color, 28))
    draw.polygon(
        [(x1 + 14, y1 + 14), (x2 - 16, y1 + 14), (x2 - 40, y1 + 46), (x1 + 36, y1 + 46)],
        fill=(*color, 38),
    )
    draw.line([(x1 + 20, y2 - 22), (x2 - 20, y2 - 22)], fill=(*color, 120), width=3)


def _render_devops_evaluation_thumbnail(out_path: Path) -> None:
    from PIL import Image, ImageDraw, ImageFilter

    img = Image.new("RGB", (TARGET_W, TARGET_H), (6, 11, 24))
    bg = Image.new("RGBA", img.size, (0, 0, 0, 0))
    bdraw = ImageDraw.Draw(bg)
    for y in range(TARGET_H):
        alpha = int(80 * (y / TARGET_H))
        bdraw.line([(0, y), (TARGET_W, y)], fill=(0, 180, 210, alpha))
    img = Image.alpha_composite(img.convert("RGBA"), bg)

    layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(layer)
    cyan = (54, 226, 236)
    emerald = (77, 224, 149)
    amber = (255, 177, 56)

    # Subtle floor grid with pure geometric lines only.
    for x in range(-160, TARGET_W + 160, 90):
        draw.line([(x, 500), (x + 300, TARGET_H)], fill=(72, 120, 150, 34), width=1)
    for y in range(470, TARGET_H, 38):
        draw.line([(0, y), (TARGET_W, y)], fill=(72, 120, 150, 28), width=1)

    lanes = [
        (155, cyan, [(90, 155), (375, 155), (575, 235), (845, 235), (1070, 155)]),
        (315, emerald, [(80, 315), (310, 315), (500, 260), (710, 365), (1080, 365)]),
        (455, amber, [(95, 455), (350, 455), (540, 405), (770, 455), (1060, 455)]),
    ]
    for _, color, points in lanes:
        _draw_glow_line(draw, layer, points, color, width=4, glow=18)
        for px, py in points[1:-1]:
            draw.ellipse((px - 10, py - 10, px + 10, py + 10), fill=(*color, 220))
            draw.ellipse((px - 23, py - 23, px + 23, py + 23), outline=(*color, 80), width=2)

    _draw_glass_block(draw, layer, (105, 245, 265, 430), cyan)
    _draw_glass_block(draw, layer, (325, 185, 500, 385), emerald)
    _draw_glass_block(draw, layer, (560, 250, 725, 475), cyan)
    _draw_glass_block(draw, layer, (820, 170, 990, 420), amber)

    # Release gates as abstract arches; no labels, text, or UI panels.
    for x, color in [(785, emerald), (955, amber)]:
        gate = Image.new("RGBA", img.size, (0, 0, 0, 0))
        gd = ImageDraw.Draw(gate)
        gd.rounded_rectangle((x, 118, x + 120, 500), radius=56, outline=(*color, 190), width=8)
        layer.alpha_composite(gate.filter(ImageFilter.GaussianBlur(16)))
        draw.rounded_rectangle((x, 118, x + 120, 500), radius=56, outline=(*color, 230), width=3)
        draw.rectangle((x + 20, 250, x + 100, 500), fill=(6, 11, 24, 170))

    for cx, cy, r, color in [(605, 155, 42, cyan), (675, 122, 24, emerald), (735, 205, 18, amber)]:
        draw.ellipse((cx - r, cy - r, cx + r, cy + r), outline=(*color, 190), width=3, fill=(*color, 28))
        draw.ellipse((cx - 5, cy - 5, cx + 5, cy + 5), fill=(*color, 230))

    img.alpha_composite(layer)
    vignette = Image.new("L", img.size, 0)
    vdraw = ImageDraw.Draw(vignette)
    vdraw.ellipse((-140, -180, TARGET_W + 140, TARGET_H + 180), fill=220)
    vignette = vignette.filter(ImageFilter.GaussianBlur(80))
    dark = Image.new("RGBA", img.size, (0, 0, 0, 80))
    img = Image.composite(img, Image.alpha_composite(img, dark), vignette)
    _save_image_pair(img.convert("RGB"), out_path)


CUSTOM_RENDERERS = {
    "data-driven-devops-platform-evaluation-2026": _render_devops_evaluation_thumbnail,
}


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Generate Neo Genesis blog thumbnails.")
    parser.add_argument("--slug", action="append", default=[], help="Only generate this slug. Repeatable.")
    parser.add_argument("--force", action="store_true", help="Regenerate even when the PNG already exists.")
    args = parser.parse_args(argv)

    _load_env()
    posts = parse_blog_posts()
    if not posts:
        return 1

    # Filter: skip KO siblings (they share the EN parent's image via the
    # slug.replace(/-ko$/, "") lookup in /blog/page.tsx)
    en_posts = [p for p in posts if not p["slug"].endswith("-ko")]
    if args.slug:
        wanted = set(args.slug)
        en_posts = [p for p in en_posts if p["slug"] in wanted]
        missing_slugs = wanted.difference(p["slug"] for p in en_posts)
        if missing_slugs:
            print(f"Unknown slug(s): {', '.join(sorted(missing_slugs))}")
            return 1
    print(f"Total BLOG_POSTS: {len(posts)} | EN candidates: {len(en_posts)}")

    missing: list[dict[str, str]] = []
    for post in en_posts:
        slug = post["slug"]
        png = BLOG_DIR / f"{slug}.png"
        if args.force or not png.exists():
            missing.append(post)

    print(f"Thumbnails to generate: {len(missing)}")
    if not missing:
        print("All thumbnails present.")
        return 0
    for post in missing:
        print(f"  - {post['slug']}")

    print()
    success = 0
    for post in missing:
        slug = post["slug"]
        out = BLOG_DIR / f"{slug}.png"
        custom_renderer = CUSTOM_RENDERERS.get(slug)
        if custom_renderer:
            print(f"=== {slug} ===")
            print("    using deterministic subject renderer")
            custom_renderer(out)
            success += 1
            continue
        prompt = _prompt_for_post(post) or GENERIC_FALLBACK
        print(f"=== {slug} ===")
        png_bytes = _hf_infer(prompt)
        if png_bytes is None:
            print(f"  [FAIL] no provider returned image")
            continue
        _letterbox_to_target(png_bytes, out)
        success += 1

    print()
    print(f"=== Summary === generated {success} / {len(missing)} missing thumbnails")
    return 0 if success == len(missing) else 2


if __name__ == "__main__":
    sys.exit(main())
