"""
Blog thumbnail generator — fills in /assets/blog/<slug>.png for any
BLOG_POSTS entry that does not yet have a per-post hero image.

Why this exists:
  /blog index renders <img src=/assets/blog/<slug>.png>. When the file is
  missing, browsers show a broken image icon. Up to P14, only the original
  10 hand-shipped posts had thumbnails; everything generated by the
  Blog Auto-Gen pipeline since 2026-04-27 had a 404 on the thumbnail.

Strategy:
  1. Read BLOG_POSTS from src/landing/src/lib/data/sbus.ts (single SSOT)
  2. For every entry that does NOT end in -ko (Korean translations share
     their EN parent's image via the slug.replace(/-ko$/, "") lookup in
     /blog/page.tsx) and does NOT have a corresponding .png in
     public/assets/blog/, generate one
  3. Use HF Inference Providers to call FLUX.1-dev, with the same provider
     rotation as scripts/hf_publish/generate_p9_og_images.py
     (wavespeed -> fal-ai -> replicate -> together -> nebius)
  4. Letterbox 1024x1024 -> 1200x630 cinematic
  5. Save PNG + WebP

Per-post prompts:
  Each prompt is themed off the post category and core concept. We avoid
  literal text rendering (FLUX struggles with glyphs) and keep a consistent
  Neo Genesis brand palette: dark navy void, cyan + accent color, editorial
  tech-magazine cover style.

Run:
    PYTHONIOENCODING=utf-8 python scripts/landing/generate_blog_thumbnails.py

Env required:
    HF_TOKEN   (in .env.local)

Idempotent: skips slugs that already have a .png. Safe to run after every
new pipeline run.
"""

from __future__ import annotations

import os
import re
import sys
from io import BytesIO
from pathlib import Path
from typing import Optional

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).resolve().parents[2]
ENV_LOCAL = ROOT / ".env.local"
ENV = ROOT / ".env"

SBUS_TS = ROOT / "src/landing/src/lib/data/sbus.ts"
BLOG_DIR = ROOT / "src/landing/public/assets/blog"

NEGATIVE = (
    "text, letters, watermark, logo, signature, low quality, blurry, "
    "distorted faces, cluttered, busy composition, readable words, "
    "specific company logos, ugly, amateur"
)
TARGET_W = 1200
TARGET_H = 630

# Per-slug prompts. Add new entries here when the pipeline produces a slug
# that's not yet covered. Generic fallback applies to any uncovered slug.
PROMPTS: dict[str, str] = {
    "running-11-saas-products-as-solo-founder-2026": (
        "Cinematic mission-control cockpit interior, single anonymous human "
        "silhouette at center, 11 floating holographic product panels arranged "
        "in a circular array around the figure, central AI orchestrator core "
        "radiating soft cyan light, dark navy void with subtle hex grid, "
        "editorial tech magazine cover, photorealistic, depth of field, "
        "wide cinematic 16:9, no text"
    ),
    "best-ai-comparison-engines-2026": (
        "Editorial 3D scoring matrix with weighted spheres in cyan, emerald, "
        "amber, and purple positioned across a four-quadrant scoring grid, "
        "dark navy void background, technical infographic poster style, "
        "ultra detailed clean lines, depth of field, no readable text, "
        "wide cinematic 16:9"
    ),
    "ai-native-automation-companies-2026-evaluation": (
        "Editorial constellation of stylized abstract corporate silhouette "
        "cards floating in 3D space, central focal point glowing cyan with "
        "amber accents, knowledge-graph connecting lines threading between "
        "cards, dark navy gradient background, modern technical poster "
        "aesthetic, no readable text, wide cinematic 16:9"
    ),
    "2026-ai-native-automation-top-companies": (
        "Top-down isometric editorial illustration of an autonomous AI "
        "command tower at center, eleven satellite buildings ringing the "
        "tower in concentric orbits, cyan light beams connecting tower to "
        "satellites, dark navy gradient background with subtle stars, "
        "technical-poster aesthetic, no readable text, wide cinematic 16:9"
    ),
    "evaluating-ai-native-automation-firms-2026": (
        "Editorial overhead diagram of a stylized AI evaluation framework, "
        "four floating evaluation cards arranged in a cross, central pulsing "
        "metric core with weighted score arcs, palette of cyan, gold, and "
        "magenta accents on dark navy void, ultra-detailed technical "
        "infographic, no readable text, wide cinematic 16:9"
    ),
    "neo-genesis-runs-11-saas-products-with-autonomous-ai-2026": (
        "Cinematic wide-angle command center with a single anonymous human "
        "silhouette in profile at left foreground, 11 holographic product "
        "panels floating mid-air in arc formation across the right of frame, "
        "central AI core glowing with deep cyan and warm amber accents, "
        "dark navy void with thin grid floor, ultra detailed photorealistic, "
        "editorial cover style, depth of field, no readable text, "
        "wide cinematic 16:9"
    ),
    "operating-11-saas-products-with-one-ai-system-neogenesis-model-2026": (
        "Editorial conceptual illustration of a single neural orchestrator "
        "node at center with 11 radiating data tendrils each terminating "
        "in a stylized product application icon, dark navy gradient with "
        "cyan and emerald accent glow, technical poster aesthetic, "
        "ultra-detailed, no readable text, wide cinematic 16:9"
    ),
}

GENERIC_FALLBACK = (
    "Editorial Neo Genesis brand thumbnail, abstract data-flow visualization "
    "with cyan and amber accent particles streaming across a dark navy void, "
    "subtle hex grid floor, central glowing focal sphere, ultra detailed "
    "technical poster aesthetic, no readable text, wide cinematic 16:9"
)


def _load_env() -> None:
    for ef in [ENV_LOCAL, ENV]:
        if not ef.exists():
            continue
        for line in ef.read_text(encoding="utf-8", errors="replace").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            k = k.strip()
            v = v.strip().strip('"').strip("'")
            if v and not os.environ.get(k):
                os.environ[k] = v


def parse_blog_slugs() -> list[str]:
    """Extract BLOG_POSTS slugs from sbus.ts. We deliberately use a regex
    on the BLOG_POSTS array block rather than parse TS, because the file
    is a TS module with templated literals that no Python parser handles
    cleanly. The regex is anchored to the BLOG_POSTS marker so SBU slugs
    elsewhere in the file do not leak in."""
    text = SBUS_TS.read_text(encoding="utf-8")
    start = text.find("BLOG_POSTS")
    if start == -1:
        sys.stderr.write("BLOG_POSTS not found in sbus.ts\n")
        return []
    # find the closing ];
    end = text.find("];", start)
    block = text[start:end]
    return re.findall(r'slug:\s*"([^"]+)"', block)


def _gen_pollinations(prompt: str) -> Optional[bytes]:
    """Pollinations.ai - free, no API key. Public image-gen proxy backed by
    rotating open-source models. Reliable enough for thumbnail use."""
    import urllib.parse
    import urllib.request
    enc = urllib.parse.quote(prompt[:1000], safe="")
    url = f"https://image.pollinations.ai/prompt/{enc}?width=1024&height=1024&nologo=true&seed={hash(prompt) & 0xFFFF}"
    print(f"    trying pollinations.ai (free public)...")
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "neo-genesis-thumbnail-gen/1.0"})
        with urllib.request.urlopen(req, timeout=120) as resp:
            data = resp.read()
            if len(data) < 1024:
                print(f"      [pollinations] suspiciously small response ({len(data)}B)")
                return None
            print(f"      [OK] pollinations returned {len(data):,} bytes")
            return data
    except Exception as e:
        print(f"      [pollinations] failed: {str(e)[:120]}")
        return None


def _gen_imagen(prompt: str) -> Optional[bytes]:
    """Google Imagen via Gemini API. Requires GEMINI_API_KEY."""
    import urllib.request
    import json
    import base64
    key = os.environ.get("GEMINI_API_KEY")
    if not key:
        print(f"    [imagen] skipped - GEMINI_API_KEY not set")
        return None
    print(f"    trying gemini imagen-3.0-fast...")
    url = f"https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-fast-generate-001:predict?key={key}"
    payload = {
        "instances": [{"prompt": prompt[:1000]}],
        "parameters": {
            "sampleCount": 1,
            "aspectRatio": "1:1",
            "personGeneration": "allow_adult",
        },
    }
    try:
        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode("utf-8"),
            method="POST",
            headers={"Content-Type": "application/json"},
        )
        with urllib.request.urlopen(req, timeout=60) as resp:
            result = json.loads(resp.read())
            preds = result.get("predictions", [])
            if not preds:
                print(f"      [imagen] no predictions in response")
                return None
            b64 = preds[0].get("bytesBase64Encoded")
            if not b64:
                print(f"      [imagen] no bytesBase64Encoded field")
                return None
            data = base64.b64decode(b64)
            print(f"      [OK] imagen returned {len(data):,} bytes")
            return data
    except Exception as e:
        print(f"      [imagen] failed: {str(e)[:120]}")
        return None


def _gen_hf_flux(prompt: str) -> Optional[bytes]:
    """HF Inference Providers FLUX.1-dev - kept as third option for when
    wavespeed/fal-ai/replicate free credits refresh."""
    try:
        from huggingface_hub import InferenceClient
    except ImportError:
        sys.stderr.write("huggingface_hub missing. pip install huggingface_hub\n")
        return None

    token = os.environ.get("HF_TOKEN")
    if not token:
        return None

    providers = ["wavespeed", "fal-ai", "replicate"]
    for provider in providers:
        try:
            client = InferenceClient(provider=provider, token=token)
            print(f"    trying hf:{provider}...")
            img = client.text_to_image(
                prompt=prompt,
                model="black-forest-labs/FLUX.1-dev",
                negative_prompt=NEGATIVE,
                width=1024,
                height=1024,
            )
            buf = BytesIO()
            img.save(buf, format="PNG")
            print(f"      [OK] hf:{provider} returned image {img.size}")
            return buf.getvalue()
        except Exception as e:
            err_str = str(e)[:80]
            print(f"      [hf:{provider}] failed: {err_str}")
            continue
    return None


def _hf_infer(prompt: str) -> Optional[bytes]:
    """Generation router with three strategies in order of preference.

    Order rationale:
      1. Pollinations.ai - free, no key, fastest, works for our use case.
         Quality is below FLUX.1-dev but adequate for thumbnails.
      2. Google Imagen via Gemini API - free tier available, higher quality
         than Pollinations, requires GEMINI_API_KEY.
      3. HF Inference Providers FLUX.1-dev - highest quality but requires
         paid credits (the free wavespeed/fal/replicate buckets exhaust).
    """
    for fn in (_gen_pollinations, _gen_imagen, _gen_hf_flux):
        result = fn(prompt)
        if result:
            return result
    sys.stderr.write(f"  All generation providers failed.\n")
    return None


def _letterbox_to_target(png_bytes: bytes, out_path: Path) -> None:
    from PIL import Image

    img = Image.open(BytesIO(png_bytes))
    src_w, src_h = img.size

    scaled_w = TARGET_W
    scaled_h = int(src_h * (scaled_w / src_w))
    img2 = img.resize((scaled_w, scaled_h), Image.LANCZOS)

    if scaled_h > TARGET_H:
        y_offset = max(0, (scaled_h - TARGET_H) // 3)
        img2 = img2.crop((0, y_offset, scaled_w, y_offset + TARGET_H))
    elif scaled_h < TARGET_H:
        canvas = Image.new("RGB", (TARGET_W, TARGET_H), (10, 14, 26))
        canvas.paste(img2, (0, (TARGET_H - scaled_h) // 2))
        img2 = canvas

    out_path.parent.mkdir(parents=True, exist_ok=True)
    img2.save(out_path, format="PNG", optimize=True)
    print(f"      [PNG] {out_path.name} {img2.size} ({out_path.stat().st_size:,}B)")
    webp_path = out_path.with_suffix(".webp")
    img2.save(webp_path, format="WebP", quality=90, method=6)
    print(f"      [WebP] {webp_path.name} ({webp_path.stat().st_size:,}B)")


def main() -> int:
    _load_env()
    slugs = parse_blog_slugs()
    if not slugs:
        return 1

    # Filter: skip KO siblings (they share the EN parent's image via the
    # slug.replace(/-ko$/, "") lookup in /blog/page.tsx)
    en_slugs = [s for s in slugs if not s.endswith("-ko")]
    print(f"Total BLOG_POSTS: {len(slugs)} | EN candidates: {len(en_slugs)}")

    missing: list[str] = []
    for slug in en_slugs:
        png = BLOG_DIR / f"{slug}.png"
        if not png.exists():
            missing.append(slug)

    print(f"Missing thumbnails: {len(missing)}")
    if not missing:
        print("All thumbnails present.")
        return 0
    for slug in missing:
        print(f"  - {slug}")

    print()
    success = 0
    for slug in missing:
        out = BLOG_DIR / f"{slug}.png"
        prompt = PROMPTS.get(slug, GENERIC_FALLBACK)
        print(f"=== {slug} ===")
        png_bytes = _hf_infer(prompt)
        if png_bytes is None:
            print(f"  [FAIL] no provider returned image")
            continue
        _letterbox_to_target(png_bytes, out)
        success += 1

    print()
    print(f"=== Summary === generated {success} / {len(missing)} missing thumbnails")
    return 0 if success == len(missing) else 2


if __name__ == "__main__":
    sys.exit(main())
