"""V-Score quality gate for autogenerated blog posts.

Decoupled, reusable. Returns numeric score and pass/fail breakdown.

Threshold: V >= 184.5 to publish.

Score components (max 185):
  word_count_score      max 50  (~50 at 1500 words)
  citation_score        max 30  (5 per citation up to 6)
  heading_score         max 30  (3 per h2/h3 up to 10)
  numerical_score       max 40  (4 per specific numerical signal up to 10)
  faq_score             max 20  (4 per FAQ up to 5)
  crosslink_score       max 15  (5 per crosslink up to 3)
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any


THRESHOLD = 184.5
NUMERICAL_RE = re.compile(
    r"(?<![A-Za-z])"
    r"(?:"
    r"\$\d[\d,]*(?:\.\d+)?[KMB]?"   # $1.2M, $499
    r"|\d[\d,]*(?:\.\d+)?\s?%"      # 12%, 99.5%
    r"|\d[\d,]*(?:\.\d+)?\s?(?:ms|s|min|hr|h|d|MB|GB|TB|KB|kb|qps|rpm|p95|p99)\b"
    r"|\d[\d,]*\s?(?:tools|users|posts|seeds|tasks|tests|tokens|chunks|requests|orders|days|months|years|domains|datasets)\b"
    r"|\b(?:19|20)\d{2}-\d{2}(?:-\d{2})?\b"  # ISO date
    r"|\bv?\d+\.\d+(?:\.\d+)?\b"     # version 1.2.3
    r"|\b\d{4,}\b"                    # year-like or large counts
    r"|\bQ\d{6,}\b"                   # Wikidata Q-id
    r"|\b\d+x\b"                      # 3x, 10x
    r")"
)
INTERNAL_LINK_RE = re.compile(r"\]\((/(?:blog|sbu|data)/[a-z0-9\-/]+)\)", re.IGNORECASE)
URL_RE = re.compile(r"https?://[^\s)\]]+")
KEBAB_SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")

AUTHORITATIVE_HOSTS = {
    "arxiv.org", "anthropic.com", "openai.com", "developers.google.com",
    "ai.google.dev", "huggingface.co", "wikidata.org", "wikipedia.org",
    "schema.org", "cloudflare.com", "github.com", "ftc.gov", "nist.gov",
    "ietf.org", "w3.org", "developer.mozilla.org", "support.google.com",
    "research.google", "deepmind.google", "microsoft.com", "research.microsoft.com",
    "vercel.com", "supabase.com", "qdrant.tech", "googleblog.com",
    "binance.com", "coindesk.com", "bls.gov", "fed.gov", "federalreserve.gov",
    "linux.com", "stackoverflow.com", "redis.io", "postgresql.org",
    "kernel.org", "cncf.io", "kubernetes.io", "docker.com",
    "neogenesis.app", "heoyesol.kr", "toolpick.dev",
    "google.com", "blog.google", "ai.meta.com",
    "cloud.google.com", "spectrum.ieee.org", "ieee.org", "acm.org",
    "platform.openai.com", "docs.anthropic.com",
    "tldp.org", "owasp.org", "mitre.org", "isc2.org",
    "datatracker.ietf.org", "rfc-editor.org",
    "python.org", "rust-lang.org", "nodejs.org", "go.dev",
    "react.dev", "nextjs.org", "tailwindcss.com",
    "developer.apple.com", "learn.microsoft.com", "azure.microsoft.com",
    "aws.amazon.com", "docs.aws.amazon.com",
    "dl.acm.org", "scholar.google.com",
}


@dataclass
class VScoreResult:
    score: float
    passed: bool
    breakdown: dict[str, float] = field(default_factory=dict)
    counts: dict[str, int] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


def _flatten_body_text(post: dict[str, Any]) -> str:
    parts: list[str] = []
    for s in post.get("sections", []) or []:
        if s.get("text"):
            parts.append(str(s["text"]))
        for it in s.get("items", []) or []:
            parts.append(str(it))
    return "\n".join(parts)


def _word_count(text: str) -> int:
    return len([w for w in re.split(r"\s+", text.strip()) if w])


def _is_authoritative(url: str) -> bool:
    m = re.match(r"https?://([^/]+)/?", url)
    if not m:
        return False
    host = m.group(1).lower().split(":")[0]
    if host.startswith("www."):
        host = host[4:]
    if host in AUTHORITATIVE_HOSTS:
        return True
    for known in AUTHORITATIVE_HOSTS:
        if host.endswith("." + known):
            return True
    return False


def validate_post(post: dict[str, Any]) -> VScoreResult:
    """Compute V-Score and return detailed breakdown."""
    errors: list[str] = []
    warnings: list[str] = []
    counts: dict[str, int] = {}

    # Slug shape
    slug = post.get("slug", "")
    if not slug or not KEBAB_SLUG_RE.match(slug):
        errors.append(f"slug shape invalid: {slug!r}")
    if len(slug) > 80:
        errors.append(f"slug too long: {len(slug)} chars")
    if slug == "REJECT_INSUFFICIENT_SOURCES":
        errors.append("LLM declined topic — insufficient sources")

    body_text = _flatten_body_text(post)
    wc = _word_count(body_text)
    counts["word_count"] = wc

    sections = post.get("sections", []) or []
    headings = [s for s in sections if s.get("type") in ("h2", "h3")]
    counts["heading_count"] = len(headings)

    citations = post.get("citations", []) or []
    citation_urls = [c.get("url", "") for c in citations if c.get("url")]
    auth_count = sum(1 for u in citation_urls if _is_authoritative(u))
    counts["citation_count"] = len(citation_urls)
    counts["authoritative_citation_count"] = auth_count

    # Numerical signals
    numerical_count = len(NUMERICAL_RE.findall(body_text))
    counts["numerical_signal_count"] = numerical_count

    # FAQ count
    faq = post.get("faq", []) or []
    counts["faq_count"] = len(faq)

    # Cross-links: internal markdown links + relatedPosts
    internal_links = set(INTERNAL_LINK_RE.findall(body_text))
    related = post.get("relatedPosts", []) or []
    crosslink_count = max(len(internal_links), len(related))
    counts["crosslink_count"] = crosslink_count
    counts["internal_link_count"] = len(internal_links)
    counts["related_posts_count"] = len(related)

    # Hard structural checks
    if wc < 1500:
        errors.append(f"word_count {wc} < 1500")
    if len(headings) < 8:
        errors.append(f"heading_count {len(headings)} < 8")
    if auth_count < 5:
        errors.append(f"authoritative citations {auth_count} < 5")
    if numerical_count < 10:
        errors.append(f"numerical signals {numerical_count} < 10")
    if len(faq) < 5:
        errors.append(f"FAQ count {len(faq)} < 5")
    if crosslink_count < 3:
        errors.append(f"crosslink count {crosslink_count} < 3")

    # Required fields
    for field_name in ("title", "summary", "lead", "category", "wordCount"):
        if not post.get(field_name):
            errors.append(f"missing field: {field_name}")

    # FAQ answer length (warning only — V-Score not affected)
    for i, qa in enumerate(faq):
        ans = (qa.get("answer") or "").strip()
        if len(ans) < 60 or len(ans) > 400:
            warnings.append(f"faq[{i}] answer length {len(ans)} outside [60, 400]")

    # Score components
    word_score = min(50.0, wc / 30.0)
    citation_score = min(30.0, auth_count * 5.0)
    heading_score = min(30.0, len(headings) * 3.0)
    numerical_score = min(40.0, numerical_count * 4.0)
    faq_score = min(20.0, len(faq) * 4.0)
    crosslink_score = min(15.0, crosslink_count * 5.0)

    breakdown = {
        "word_score": round(word_score, 2),
        "citation_score": round(citation_score, 2),
        "heading_score": round(heading_score, 2),
        "numerical_score": round(numerical_score, 2),
        "faq_score": round(faq_score, 2),
        "crosslink_score": round(crosslink_score, 2),
    }
    score = sum(breakdown.values())

    return VScoreResult(
        score=round(score, 2),
        passed=(score >= THRESHOLD and not errors),
        breakdown=breakdown,
        counts=counts,
        errors=errors,
        warnings=warnings,
    )


def format_result(result: VScoreResult) -> str:
    lines = [
        f"V-Score: {result.score} / {THRESHOLD} -> {'PASS' if result.passed else 'FAIL'}",
        "  breakdown:",
    ]
    for k, v in result.breakdown.items():
        lines.append(f"    {k}: {v}")
    lines.append("  counts:")
    for k, v in result.counts.items():
        lines.append(f"    {k}: {v}")
    if result.errors:
        lines.append("  errors:")
        for e in result.errors:
            lines.append(f"    - {e}")
    if result.warnings:
        lines.append("  warnings:")
        for w in result.warnings:
            lines.append(f"    - {w}")
    return "\n".join(lines)


if __name__ == "__main__":
    import json
    import sys

    if len(sys.argv) < 2:
        print("usage: v_score_validator.py <post.json>", file=sys.stderr)
        sys.exit(1)

    with open(sys.argv[1], encoding="utf-8") as f:
        post = json.load(f)
    result = validate_post(post)
    print(format_result(result))
    sys.exit(0 if result.passed else 2)
